### ISSUE TITLE
Runs on all files in directory, not just my project

### ISSUE THREAD

**Issue by onlynone** [CraigJPerry/setuptools-pep8#5]
When I run:

```
python setup.py nosetests
```

It downloads several packages, like `nose-1.3.0-py2.7.egg` to the current directory (I kind of wish these would go into the virtualenv I have defined, but that's a different story). Then when I run:

```
python setup.py pep8
```

It runs `pep8` on all these dependencies that were downloaded. I don't really care if there are issues in `nose` or `coverage`. I'd like it to just run on my package/module. It looks like `setuptools-pylint` is able to do this.

**Comment by CraigJPerry** [comment]
Before doing `python setup.py nosetests` do a `pip install .` that will install the deps to your virtualenv site packages instead of the package dir.

The above solves your problem, but if you find another use case for skipping dirs, you can configure them with `python setup.py pep8 --exclude dir1/,dir2/,dir3/` or you can add a pep8 stanza to your package's setup.cfg file so you don't need to specify --exclude every time:

```
$ cat setup.cfg
[pep8]
exclude = dir1, dir2, dir3
...
```
